### ISSUE TITLE
I need use variable in externalSNS topic name

### ISSUE THREAD

**Issue by anasinnyk-atb** [silvermine/serverless-plugin-external-sns-events#3]
For example:
```
functionName:
    handler: lambda.handler
    events:
      - externalSNS: ${self:provider.stage}-topic-name
```
